version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.10.0
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Build Docker Image
          command: docker build -t portfolio-app .
      - run:
          name: Save Docker Image to Tar
          command: docker save -o portfolio-app.tar portfolio-app
      - persist_to_workspace:
          root: .
          paths:
            - portfolio-app.tar

  deploy:
    docker:
      - image: docker:19.03.12
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Copy Docker Image to Remote
          command: scp -oStrictHostKeyChecking=no /workspace/portfolio-app.tar $USER@$DNS:/home/ubuntu/
      - run:
          name: Load Docker Image on Remote
          command: ssh -oStrictHostKeyChecking=no $USER@$DNS "docker load -i /home/ubuntu/portfolio-app.tar"
      - run:
          name: Run Docker Container on Remote
          command: ssh -oStrictHostKeyChecking=no $USER@$DNS "docker run -d -p 80:3000 portfolio-app"

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build