version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: docker build -t portfolio-app .
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Transfer and Load Docker Image on Remote
          command: |
            docker save portfolio-app | bzip2 | pv | ssh -oStrictHostKeyChecking=no $USER@$DNS "docker load"
      - run:
          name: Run Docker Container on Remote
          command: ssh -oStrictHostKeyChecking=no $USER@$DNS "docker run -d -p 80:3000 portfolio-app"

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
